/**
 * @aethel/tokens
 *
 * Design tokens for the Aethel Design System.
 * This file serves as the TypeScript entry point.
 * The actual token values are generated by Style Dictionary from JSON sources.
 */

export {};
